### ISSUE TITLE
Error instead of thumbnail for empty circles

### ISSUE THREAD

**Issue by jeroenrnl** [jeroenrnl/zoph#102]
When creating a new circle, and no people are yet assigned to it, the following error is displayed instead of a thumbnail:

``` string(956) "#0 /var/www/photo/htdocs/classes/db/db.inc.php(134): PDO->prepare('SELECT p.photo_...')
#1 /var/www/photo/htdocs/classes/zophTable.inc.php(633): db\db::query(Object(db\select))
#2 /var/www/photo/htdocs/classes/circle.inc.php(174): zophTable::getRecordsFromQuery(Object(db\select))
#3 /var/www/photo/htdocs/classes/zophTable.inc.php(687): circle->getAutoCover('highest')
#4 /var/www/photo/htdocs/templates/default/blocks/view_thumbs.tpl.php(29): zophTable->displayAutoCover('highest')
#5 /var/www/photo/htdocs/classes/template/template.inc.php(125): include('/var/www/photo/...')
#6 /var/www/photo/htdocs/classes/template/template.inc.php(212): template\template->__toString()
#7 /var/www/photo/htdocs/templates/default/organizer.tpl.php(60): template\template->displayBlocks()
#8 /var/www/photo/htdocs/classes/template/template.inc.php(125): include('/var/www/photo/...')
#9 /var/www/photo/htdocs/people.php(178): template\template->__toString()
#10 {main}"
SELECT p.photo_id AS photo_id, ar.rating AS rating, count(person_id) AS count, ar.rating FROM zoph_photos AS p INNER JOIN zoph_photo_people AS ppl ON p.photo_id=ppl.photo_id INNER JOIN zoph_view_photo_avg_rating AS ar ON p.photo_id=ar.photo_id WHERE (ppl.person_id IN ()) GROUP BY photo_id ORDER BY count DESC, ar.rating DESC LIMIT 1;SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ')) GROUP BY photo_id ORDER BY count DESC, ar.rating DESC LIMIT 1' at line 1
<b>Fatal Error</b>: SQL failed <tt>db.inc.php</tt>: 159.<br>
fatal error```

**Comment by jeroenrnl** [comment]
38165cb9fef45eddb1c6b46d7bb9af90743baab2
